# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlipDecks' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlipDecks
pod 'Charts', '~> 3.0.1'
  target 'FlipDecksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlipDecksUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
